# Generated by Django 3.0.6 on 2020-06-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
