# Generated by Django 3.0.6 on 2020-05-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(to='activity.Activity', verbose_name='Activity'),
        ),
    ]
