# Generated by Django 3.0.6 on 2020-05-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
    ]
