# Generated by Django 3.0.6 on 2020-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_user_activities'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='week',
            field=models.ManyToManyField(to='week.Week', verbose_name='Activity'),
        ),
    ]
