# Generated by Django 3.0.6 on 2020-05-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0001_initial'),
        ('authapp', '0004_user_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='week',
        ),
        migrations.AddField(
            model_name='user',
            name='week',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='week.Week'),
        ),
    ]
